baseURL               = "https://www.gz.mk"
languageCode          = "zh-CN"
title                 = "Monlor's WebStack"
theme                 = "WebStack-Hugo"
preserveTaxonomyNames = true
disablePathToLower    = true
hasCJKLanguage        = true
publishDir            = "public"

[params]
    author        = "monlor"
    description   = "My Website Directory which is Based on WebStack-Hugo"
    upload        = "https://t.gz.mk"
    about         = "https://github.com/monlor/WebStack"	# 左侧导航栏的"关于我们"页面(./about)
    repository    = "https://github.com/monlor/WebStack"	
    enablePreLoad = true                                                        # 网站完全打开前预加载动画
    textPreLoad   = "Monlor's WebStack"                                              # 预加载的动画文字, 只有当enablePreLoad=true时生效
    expandSidebar = false                                                       # 默认展开左侧边导航栏
    logosPath     = "https://cdn.monlor.com/webstack/logos"	                # 网站每个导航地址logo存放地址
    defaultLogo   = "https://cdn.monlor.com/webstack/logos/default.webp"    # logo图片资源不存在或者错误时, 默认显示的logo; 该参数如为空,将会一直加载对应的logo,直至成功
    nightMode     = false							                            # 默认站点为深色(夜间)模式
    yiyan         = true                                        		        # 默认启用一言服务

[params.seo]
    baiduhmid       = ''             		# 百度统计 hm.src 的 ID
    baiduSiteVer    = ''                    # 百度HTML标签验证(baidu-site-verification)    
    tj51laid        = ''                    # 51.LA 网站统计
    tj51lack        = ''
    GoogleAdsClient = ''

[params.qweather]
    key = "085791e805a24491b43b06cf58ab31e7"

[params.images]
    favicon           = "https://cdn.monlor.com/webstack/sites/favicon.png"
    searchImageL      = "https://cdn.monlor.com/webstack/banner/bg-dna.jpg"		  # 搜索部分浅色背景图
    searchImageD      = "https://cdn.monlor.com/webstack/banner/bg-dna.jpg"		  # 搜索部分深色背景图
    logoExpandLight   = "https://cdn.monlor.com/webstack/sites/bt8-expand-light.png"
    logoExpandDark    = "https://cdn.monlor.com/webstack/sites/bt8-expand-dark.png"
    logoCollapseLight = "https://cdn.monlor.com/webstack/sites/bt.png"
    logoCollapseDark  = "https://cdn.monlor.com/webstack/sites/bt.png"

[markup.goldmark.renderer]
    unsafe = true

[params.footer]
    copyright = "If any content sourced from the internet violates your rights, please contact me via email: <a href=\"mailto:me@monlor.com?subject=Feedback on Monlor's WebStack\" target=\"_blank\">me@monlor.com</a>"
