name: Hugo Actions # 名字自取

on:
  workflow_dispatch:
  push:
    branches:
      - main  # 这里的意思是当 main 分支发生 push 的时候，运行下面的 jobs

jobs:
  deploy: 
    runs-on: ubuntu-20.04	# 在什么环境运行任务
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - uses: actions/checkout@v3   # 引用actions/checkout这个action，与所在的github仓库同名
        with:
         submodules: true  # Fetch Hugo themes (true OR recursive) 获取submodule主题
         fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo	# 步骤名自取
        uses: peaceiris/actions-hugo@v2	# hugo官方提供的action，用于在任务环境中获取hugo
        with:
          hugo-version: '0.59.0'	# 获取指定版本的hugo
          # extended: true

      - name: Build 
        #run: hugo --minify	# 使用 hugo 构建静态网页
        run: hugo         	# 使用 hugo 构建静态网页

      - name: Deploy Pages              # 部署至当前仓库的其他分支
        uses: peaceiris/actions-gh-pages@v3	# 一个自动发布github pages的action
        with:
          external_repository: ${{ github.repository }}
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public	
          publish_branch: pages	# 发布到哪个branch
          force_orphan: true
          full_commit_message: ${{ github.event.head_commit.message }}
          
